[package]
name = "keystore"
version = "0.1.0"
edition = "2021"


[dependencies]
security-framework = "2.4"
ed25519-dalek = { version = "2.1.0", features = ["rand_core"] }
rand = "0.8.4"
dotenv = "0.15.0"
hex = "0.4.3"
aes-gcm = "0.10.3"
mockall = { version = "0.12.1", optional = true }

[features]
mocking = ["mockall"]